- hosts: all
  become: yes
  tasks:
  - ping:
  # - rpm_key:
  #     state: present
  #     key: "{{ item }}"
  #   with_items:
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2023
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2022
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2021
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2020
  #     - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  #     - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  #     - https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  #     - https://repo.mysql.com/RPM-GPG-KEY-mysql
  # - dnf:
  #     name:
  #     - nginx
  #     - git
  #     - nano
  #     - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  #     - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
  #     - https://repo.mysql.com/mysql80-community-release-el9.rpm
  #     # - php74-build
  #     # - php-cli
  #     # - php-fpm
  #     # - mysql-server
  #     state: latest



  # - dnf:
  #     name:
  #     - mysql-community-server
  #     - mysql-community-common
  #     - mysql-community-client
  #     # - mysql-community-lib

  # - dnf:
  #     name:
  #     - php74-build
  #     - php74-php
  #     - php74-php-common
  #     - php74-php-cli
  #     - php74-php-fpm
  #     - php74-php-pdo
  #     - php74-php-ldap
  #     - php74-php-pecl-crypto
  #     - php74-php-pecl-mcrypt
  #     - php74-php-pecl-scrypt
  #     - php74-php-pecl-xxtea
  #     - php74-php-sodium
  #     - php74-php-xml
  #     - php74-php-json
  #     - php74-php-pecl-json-post
  #     - php74-php-pecl-jsonpath
  #     - php74-php-pecl-simdjson
  #     - php74-php-mbstring
  #     - php74-php-pear
  #     - php74-php-mysqlnd
  #     - php74-php-pecl-mysql
  #     - https://repo.mysql.com/mysql80-community-release-el9.rpm

  #     update_cache: true
  #     state: latest

  # - ansible.builtin.file:
  #     path: /opt/phpipam
  #     state: directory
  #     mode: '0755'

  # - ansible.builtin.git:
  #     repo: 'https://github.com/phpipam/phpipam.git'
  #     dest: /opt/phpipam
  #     clone: yes
  #     update: yes
  #     accept_hostkey: yes
  #     # accept_newhostkey: yes
  #     recursive: true
  #     version: origin/1.5


  - systemd:
      name: "{{ item }}"
      state: started
      enabled: True
    with_items:
      - mysqld
      - nginx
      - php74-php-fpm




#     pdo, pdo_mysql : Adds support for mysql connections
#     session : Adds persistent session support
#     sockets : Adds sockets support
#     openssl : Adds openSSL support
#     gmp : Adds support for dev-libs/gmp (GNU MP library) -> to calculate IPv6 networks
#     ldap : Adds LDAP support (Lightweight Directory Access Protocol – for AD also)
#     crypt : Add support for password encryption
#     SimpleXML: Support for SimpleXML (optional, for RIPE queries and if required for API)
#     json: Enable JSON support
#     gettext: Enables translation
#     filter : Adds filtering support
#     pcntl : Add support for process creation functions (optional, required for scanning)
#     cli : Enable CLI (optional, required for scanning and status checks)
#     mbstring : Enable mbstring support

# docker run -ti redhat/ubi9

# dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
# dnf install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm
#   - file:
#         path: "/etc/apt/sources.list.d/{{ item }}"
#         state: absent
#     with_items:
#         - sources.list.d/download_newrelic_com_infrastructure_agent_linux_apt.list
#         - sources.list.d/apt_newrelic_com_debian.list

#   - apt_key:
#       state: present
#       url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg

#   - apt_repository: "repo='deb [arch=amd64] http://download.newrelic.com/infrastructure_agent/linux/apt {{ansible_distribution_release}} main' state=present update_cache=yes"

#   - apt:
#         name: newrelic-infra

#   - service:
#         name: newrelic-infra
#         enabled: yes
#         state: started