# : ansible-galaxy collection install community.mysql

- hosts: all
  become: yes
  vars_files:
    - ./ansible_variables.yaml

  tasks:
  - ping:

  - ansible.builtin.file:
      path: "/root/packages/mariadb"
      state: directory
      mode: '0755'
      owner: root
      group: root

  - ansible.builtin.file:
      path: "/root/packages/dnf"
      state: directory
      mode: '0755'
      owner: root
      group: root

  - ansible.posix.synchronize:
#   - ansible.builtin.copy:
      src: packages/mariadb/    # note the '/' <-- !!!
      dest: /root/packages/mariadb/

  - ansible.posix.synchronize:
#   - ansible.builtin.copy:
      src: packages/dnf/    # note the '/' <-- !!!
      dest: /root/packages/dnf/

  - name: Install MariaDB
    ansible.builtin.shell:  sudo dnf install *.rpm --disablerepo=* --assumeyes
    args:
        chdir: /root/packages/mariadb/

  - name: Install everything else
    ansible.builtin.shell:  sudo dnf install *.rpm --disablerepo=* --assumeyes --skip-broken
    args:
        chdir: /root/packages/dnf/

  - ansible.builtin.copy:
      src: packages/phpipam.tar.xz
      dest: /root/packages

  - ansible.builtin.shell:  setenforce 0

  - ansible.posix.selinux:
      state: disabled


  - ansible.builtin.copy:
      src: ./files/etc_environment
      dest: /etc/environment
      owner: root
      group: root
      mode: '0644'

  - ansible.builtin.copy:
      src: ./files/php.ini
      dest: /etc/php.ini
      owner: root
      group: root
      mode: '0644'

  - systemd:
      name: "php-fpm"
      state: restarted
      enabled: True

  - ansible.builtin.copy:
      src: ./files/nginx_phpipam.conf
      dest: /etc/nginx/conf.d/nginx_phpipam.conf
      owner: root
      group: root
      mode: '0644'

  - systemd:
      name: nginx
      state: restarted
      enabled: True

  - systemd:
      name: mariadb
      state: started
      enabled: True


  - ansible.builtin.unarchive:
      src: /root/packages/phpipam.tar.xz
      dest: /var/www/html/
      remote_src: yes


  - ansible.builtin.file:
      path: "/var/www/html/{{ item }}"
      state: directory
      mode: '0777'
    with_items:
      - app/admin/import-export/upload/
      - app/subnets/import-subnet/upload/
      - css/images/logo/

  - name: MYSQL - Change root user password. Ignore if it fails
    mysql_user:
      # here we set a root password
      # only works on the firs time
      # will fail in the future but we don't care
      name: root
      password: "{{ mysql_root_password }}"
      # check_implicit_admin: true
      # login_user: mysql
      # login_unix_socket: /var/run/mysqld/mysqld.sock
      login_unix_socket: /var/lib/mysql/mysql.sock
    ignore_errors: true

  - ansible.builtin.template:
      src: ./files/phpipam_config.php
      dest: /var/www/html/config.php
      owner: root
      group: apache
      mode: '0640'

