# : ansible-galaxy collection install community.mysql.

- hosts: all
  become: yes
  vars_files:
    - ./ansible_variables.yaml

  tasks:
  - ping:


  - ansible.builtin.file:
      path: "/var/cache/dnf"
      state: directory
      mode: '0755'
      owner: root
      group: root

  - ansible.builtin.copy:
      src: packages/dnf/    # note the '/' <-- !!!
      dest: /var/cache/dnf/

  - ansible.builtin.copy:
      src: packages/phpipam.tar.xz
      dest: /root

  - ansible.builtin.shell:  setenforce 0

  - ansible.posix.selinux:
      state: disabled


  - ansible.builtin.copy:
      src: ./files/etc_environment
      dest: /etc/environment
      owner: root
      group: root
      mode: '0644'



  - dnf:
      name:
      # - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      # - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - net-tools
      - telnet
      - nginx
      - nano
      - mariadb-server
      - python3-PyMySQL.noarch # for ansible to talk to mysql
      - php
      - php-cli
      - php-gd
      - php-fpm
      - php-common
      - php-ldap
      - php-pdo
      - php-mysqlnd
      - php-pear
      - php-snmp
      - php-xml
      - php-mbstring
      # - php-mcrypt
      - php-gmp

  - ansible.builtin.copy:
      src: ./files/php.ini
      dest: /etc/php.ini
      owner: root
      group: root
      mode: '0644'

  - systemd:
      name: "php-fpm"
      state: restarted
      enabled: True

  - ansible.builtin.copy:
      src: ./files/nginx_phpipam.conf
      dest: /etc/nginx/conf.d/nginx_phpipam.conf
      owner: root
      group: root
      mode: '0644'

  - systemd:
      name: nginx
      state: restarted
      enabled: True

  - systemd:
      name: mariadb
      state: started
      enabled: True


  ansible.builtin.unarchive:
    src: /root/phpipam.tar.xz
    dest: /var/www/html/
    remote_src: yes

  # - ansible.builtin.git:
  #     repo: 'https://github.com/phpipam/phpipam.git'
  #     dest:  /var/www/html/
  #     clone: yes
  #     update: yes
  #     accept_hostkey: yes
  #     # accept_newhostkey: yes
  #     recursive: true
  #     version: origin/1.5

  - ansible.builtin.file:
      path: "/var/www/html/{{ item }}"
      state: directory
      mode: '0777'
    with_items:
      - app/admin/import-export/upload/
      - app/subnets/import-subnet/upload/
      - css/images/logo/

  - name: MYSQL - Change root user password. Ignore if it fails
    mysql_user:
      # here we set a root password
      # only works on the firs time
      # will fail in the future but we don't care
      name: root
      password: "{{ mysql_root_password }}"
      # check_implicit_admin: true
      # login_user: mysql
      # login_unix_socket: /var/run/mysqld/mysqld.sock
      login_unix_socket: /var/lib/mysql/mysql.sock
    ignore_errors: true



  # this is created by the UI on the first launch for us


  # - community.mysql.mysql_db:
  #     name: phpipamdb
  #     state: present

  #     login_host: 127.0.0.1
  #     login_user: root
  #     login_password: "{{ mysql_root_password }}"

  # - mysql_user:
  #     name: phpipamuser
  #     password: "{{ mysql_phpipam_password }}"
  #     host: '%'
  #     priv:
  #       'phpipamdb.*': 'ALL,GRANT'

  #     login_host: 127.0.0.1
  #     login_user: root
  #     login_password: "{{ mysql_root_password }}"

#  GRANT ALL on phpipamdb.* to phpipamdb@localhost identified by ‘phpipamadmin’;
  - ansible.builtin.template:
      src: ./files/phpipam_config.php
      dest: /var/www/html/config.php
      owner: root
      group: apache
      mode: '0640'







      # - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      # - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
      # - https://repo.mysql.com/mysql80-community-release-el9.rpm
      # - php74-build

  # - rpm_key:
  #     state: present
  #     key: "{{ item }}"
  #   with_items:
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2023
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2022
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2021
  #     - https://rpms.remirepo.net/RPM-GPG-KEY-remi2020
  #     - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  #     - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  #     - https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  #     - https://repo.mysql.com/RPM-GPG-KEY-mysql
  # - dnf:
  #     name:
  #     - nginx
  #     - git
  #     - nano
  #     - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  #     - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
  #     - https://repo.mysql.com/mysql80-community-release-el9.rpm
  #     # - php74-build
  #     # - php-cli
  #     # - php-fpm
  #     # - mysql-server
  #     state: latest



  # - dnf:
  #     name:
  #     - mysql-community-server
  #     - mysql-community-common
  #     - mysql-community-client
  #     # - mysql-community-lib

  # - dnf:
  #     name:
  #     - php74-build
  #     - php74-php
  #     - php74-php-common
  #     - php74-php-cli
  #     - php74-php-fpm
  #     - php74-php-pdo
  #     - php74-php-ldap
  #     - php74-php-pecl-crypto
  #     - php74-php-pecl-mcrypt
  #     - php74-php-pecl-scrypt
  #     - php74-php-pecl-xxtea
  #     - php74-php-sodium
  #     - php74-php-xml
  #     - php74-php-json
  #     - php74-php-pecl-json-post
  #     - php74-php-pecl-jsonpath
  #     - php74-php-pecl-simdjson
  #     - php74-php-mbstring
  #     - php74-php-pear
  #     - php74-php-mysqlnd
  #     - php74-php-pecl-mysql
  #     - https://repo.mysql.com/mysql80-community-release-el9.rpm

  #     update_cache: true
  #     state: latest

  # - ansible.builtin.file:
  #     path: /opt/phpipam
  #     state: directory
  #     mode: '0755'



  # - systemd:
  #     name: "{{ item }}"
  #     state: started
  #     enabled: True
  #   with_items:
  #     - mysqld
  #     - nginx
  #     - php74-php-fpm




#     pdo, pdo_mysql : Adds support for mysql connections
#     session : Adds persistent session support
#     sockets : Adds sockets support
#     openssl : Adds openSSL support
#     gmp : Adds support for dev-libs/gmp (GNU MP library) -> to calculate IPv6 networks
#     ldap : Adds LDAP support (Lightweight Directory Access Protocol – for AD also)
#     crypt : Add support for password encryption
#     SimpleXML: Support for SimpleXML (optional, for RIPE queries and if required for API)
#     json: Enable JSON support
#     gettext: Enables translation
#     filter : Adds filtering support
#     pcntl : Add support for process creation functions (optional, required for scanning)
#     cli : Enable CLI (optional, required for scanning and status checks)
#     mbstring : Enable mbstring support

# docker run -ti redhat/ubi9

# dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
# dnf install -y https://rpms.remirepo.net/enterprise/remi-release-9.rpm
#   - file:
#         path: "/etc/apt/sources.list.d/{{ item }}"
#         state: absent
#     with_items:
#         - sources.list.d/download_newrelic_com_infrastructure_agent_linux_apt.list
#         - sources.list.d/apt_newrelic_com_debian.list

#   - apt_key:
#       state: present
#       url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg

#   - apt_repository: "repo='deb [arch=amd64] http://download.newrelic.com/infrastructure_agent/linux/apt {{ansible_distribution_release}} main' state=present update_cache=yes"

#   - apt:
#         name: newrelic-infra

#   - service:
#         name: newrelic-infra
#         enabled: yes
#         state: started